# Generated by Django 2.1.5 on 2021-08-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usercode', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('passwd', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('deptcode', models.CharField(max_length=32)),
                ('registertime', models.CharField(max_length=19)),
                ('lastlogin', models.CharField(default=None, max_length=19)),
                ('lastloginip', models.CharField(default=None, max_length=32)),
                ('seqnum', models.IntegerField(default=None)),
            ],
        ),
    ]
